name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic tests
      env:
        FLASK_ENV: development
      run: |
        python3 -c "import webapp.app; print('✅ App imports successfully')"
        python3 -c "from src.services.consolidated_llm_service import ConsolidatedLLMService; print('✅ Services import successfully')"
    
    - name: Check code quality
      env:
        FLASK_ENV: development
      run: |
        python3 -m py_compile run_app.py
        python3 -m py_compile webapp/app.py
        echo "✅ Code compiles successfully"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Render
      run: |
        echo "🚀 Deployment triggered for main branch"
        echo "Render will automatically deploy from GitHub"
        echo "Check your Render dashboard for deployment status"